### ISSUE TITLE
Erro de configuração no Context do EF

### ISSUE THREAD

**Issue by johnnyasantoss** [marlonluft/Bludata-PagueVeloz#1]
Olá!

Tem um problema no contexto da aplicação quando ela está rodando em uma máquina que não tenha o MySql instalado.

Pra mim resolveu, só adicionando a anotação `[DbConfigurationType(typeof(MySqlEFConfiguration))]` na classe `Context`.

Dica: _Recomendo testar suas aplicações usando docker_ 👍 

Aqui uma ajuda.
https://pt.stackoverflow.com/questions/185638/the-ado-net-provider-with-invariant-name-mysql-data-mysqlclient-is-either-not/185683#185683

**Comment by marlonluft** [comment]
Olá, 
Realmente eu tenho o MySql instalado e o problema não ocorreu.
Adicionei o data annotation como você mencionou.

Referente ao Docker, eu nunca utilize, mas vou pesquisar sobre.
